config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'products#index'
  resources :products
  resources :orders
  resources :carts do 
    post 'add_to_cart/:product_id', to: 'carts#add_to_cart', as: 'add_to_cart'
    post 'remove_from_cart/item_id', to: 'carts#remove_from_cart', as: 'remove_from_cart'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in) 
      if user.type == "Admin"
        can :manage, :all
        cannot [:add_to_cart], Product
      else
        can [:read,:add_to_cart,:remove_from_cart], Product
    end
  end
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items, dependent: :destroy
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/customer.rb
class Customer < User
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user 
	has_many :order_items, dependent: :destroy
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order
end

app/models/product.rb
class Product < ApplicationRecord
    
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy

  belongs_to :user
	has_one_attached :image

	validates :product_name, presence: true
 	validates :description, presence: true, length: { minimum: 10 }
 	validates :price, presence: true

  default_scope { order(created_at: :desc)}
    
 	 
        scope :between_range, -> (min,max){
            where("price >= ? AND price <= ?", min,max)
        }
    
end

app/models/user.rb
class User < ApplicationRecord
  has_one :cart, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :orders , dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
    after_create :initialize_session

    def initialize_session
      Cart.create(user_id: self.id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :mobile])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :mobile])
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def add_to_cart
    product = Product.find(params[:product_id])
    cart = current_user.cart
    cart_items = cart.cart_items
    item = cart_items.find_by(product_id: product.id)
    if  item
      item.quantity += 1
      item.total = item.quantity * product.price
      item.save
    else
      cart_items.create(product_id: product.id, quantity: 1, total: product.price)    
    end
    cart.update(total_price: cart_items.pluck(:total).reduce(:+))
    redirect_to root_path
  end

  def remove_from_cart
    cart = current_user.cart
    cart_items = cart.cart_items
    item  = cart_items.find_by(id: params[:item_id])
    if item && item.quantity > 1
      item.quantity -= 1
      item.total = item.quantity * item.product.price
      item.save
    elsif item && item.quantity == 1
      item.destroy
    end
    cart.update(total_price: cart_items.pluck(:total).reduce(:+))
    redirect_to root_path
  end
end
 

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    ORDER_PER_PAGE = 5
    
    def index
        @orders = Order.all 
        @page = params.fetch(:page, 0).to_i
        @orders = Order.offset(@page*ORDER_PER_PAGE).limit(ORDER_PER_PAGE)
    end

    def create
        @order = Order.new()
        @order.user_id = current_user.id
        @order.save
        order_items = current_user.cart.cart_items
        order_items.each do |order_item|
            @order_item = OrderItem.new()
            @order_item.product_id = order_item.product_id
            @order_item.order_id = @order.id
            @order_item.total_price = order_item.total
            @order_item.save    
            current_user.cart.cart_items.destroy_all
        end
            redirect_to root_path, notice: 'Your Order successfully Placed!.'
            PostMailer.order_placed_email(current_user).deliver 
    end
end
    

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  PRODUCT_PER_PAGE = 3

  def index
    @cart = current_user&.cart
      if params[:filter] || params[:filter1]
        @filter0 = params[:filter]
        @filter1 = params[:filter1]
        @products = Product.between_range(@filter0,@filter1)
      else
        @page = params.fetch(:page, 0).to_i
        @products = Product.offset(@page*PRODUCT_PER_PAGE).limit(PRODUCT_PER_PAGE)
    end
  end

  def show
  end

  def new
     @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
      if @product.save
        redirect_to @product, notice: 'Product was successfully created.'
      else
        render :new
      end
  end

  def edit
     @product = Product.find(params[:id])
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.' 
  end

  private
    def product_params
      params.require(:product).permit(:product_name, :description, :price, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart.html.erb
<% if user_signed_in? && current_user.type != "Admin"%>
<details>
  <summary>Cart</summary>
  <ul>
    <% if @cart&.cart_items&.empty? %>
    <p> No items in cart</p>
    <% else %>
    <% @cart.cart_items.each do |cart_item| %>
<table class="table">
  <thead>
    <tr></tr>
      <th scope="col">Product Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tr>
    <%#byebug%>
      <td><%= cart_item.product.product_name %></td>
      <td><%= cart_item.quantity %></td>
      <td><%=  cart_item.total %></td>
      <td><%= link_to 'Remove Item',  cart_remove_from_cart_path(item_id: cart_item.id, cart_id: current_user.cart.id), :method => :post %></td>
       <% end %>
    </tr>
</table>
     <hr>
      <p>Total <%= @cart.total_price %></p>
      <%= button_to 'Pay', orders_path(user_id: current_user.id), :method => :post, data: { confirm: 'Are you sure? to placed order' } %>
      <% end %>
</details>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>Ecommerce</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <br>
      <% if user_signed_in? %>
        <h5>Welcome : <%= current_user.username %></h5>
      <%end%>

     <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield  %>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script> 
  </body>
</html>

app/views/orders/index.html.erb
<% if user_signed_in? && current_user.type != "Admin" %>
	 <h4>Your order details</h4> </br>
		<% current_user.orders.each do |order| %>
		<table class="table">
			<thead>
				<tr>
					<th scope="col">Your Order ID</th>
				</tr>
			</thead>
			<tr>
				<td><%= order.id %></td>
			</tr>
		</table>
	<% end %>
<% else %>
<h4>All orders Details</h4>
	<% @orders.each do |order| %>
	<table class="table">
  <thead>
    <tr>
    	<th scope="col">User ID</th>
    	<th scope="col">Customer Name</th>
    	<th scope="col">Email</th>
    	<th scope="col">Phone No</th>
      <th scope="col">Order ID</th>
      <th scope="col">Date-Time</th>
    </tr>
  </thead>
  <tr>
  	
  	<td><%= order.user_id %></td>
  	<% user = User.find(order.user_id) %>
  	<td><%= user.username %></td>
  	<td><%= user.email %></td>
  	<td><%= user.mobile %></td>
    <td><%= order.id %></td>
    <td><%= order.created_at %></td>
  </tr>
	</table>
	<% end %>		
	</br>
		<% if @page.present? %>
		  <div>
		    <% if @page > 0 %>
		    <%= link_to "Last Page", orders_path(page: @page - 1) %> |
		    <% end %>
		    <%= link_to "Next Page", orders_path(page: @page + 1) %>
		  </div>
		<% end %>
<% end %>

app/views/products/_filter.html.erb
<details>
	<summary>Filter Price</summary>
		<%= form_for "",url: products_path, role: "search", method: :get do %>
			<%= number_field_tag :filter, @filter0, placeholder: "0",style:'width:80px;' %>
			<%= number_field_tag :filter1, @filter1, placeholder: "100",style:'width:80px;' %>
				<%= submit_tag "Filter" %>
		<% end %><br>
</details>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

   <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<%= render 'filter' %>
<%= render 'carts/cart', product: @product %>
<h1 style="margin-left: 431px">Products</h1> <hr>

<% @products.each do |product| %>
  <div class="row"></div>
    <div class="col-md-4 card mt-4 bg-ligt">
      <div class="card-body">
        <%= image_tag(product.image, style:'width:100px;') %>
        <h5 class="card-title">Product Name - <%= product.product_name %></h5>
        <p class="card-text">Description - <%= product.description %></p>
        <h6 class="card-text">Price - <%= product.price %> Rs</h6>
          <td><%= link_to 'Show', product %></td>

            <% if can? :update, product %>
              |<td><%= link_to 'Edit', edit_product_path(product) %></td> |
              <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>

            <% if user_signed_in? %>
            <% if current_user.type != "Admin" %>
              <%= button_to 'Add to cart',  cart_add_to_cart_path(product_id: product, cart_id: current_user.cart.id), :method => :post %>
              <% end %>
            <% else %>
            <td><%= button_to 'Add to cart', new_user_session_path %></td>
            <% end %>
      </div>
    </div>
<%end%>
</br>
<% if @page.present? %>
  <div>
    <% if @page > 0 %>
    <%= link_to "Last Page", root_path(page: @page - 1) %> |
    <% end %>
    <%= link_to "Next Page", root_path(page: @page + 1) %>
  </div>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>
<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div >
  <%= image_tag(@product.image, style:'width:100px; ') %>
</div>
<p>
  <strong>Product Name:</strong>
  <%= @product.product_name %>
</p>
<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<% if can? :update, @product %>
  <%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>
  <%= link_to 'Back', products_path %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="/">Online Store</a>&nbsp
  <ul class="navbar-nav ml-auto">
      <li class="nav-item">
           <%= link_to 'Add Product', new_product_path if can? :update, @product %>
      </li>&nbsp &nbsp &nbsp
      <li class="nav-item">
           <%= link_to 'Order details', orders_path if can? :update, @product %>
      </li>
    </ul>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if user_signed_in? %>
        <% if current_user.type != "Admin" %>
        <li class="nav-item">
          <strong>
            <%= link_to "Your Orders", orders_path, class: 'nav-link' %>
        </li>
          </strong>
        <% end %>
          
      <li class="nav-item">
        <strong>
        <%= link_to "Update Profile", edit_user_registration_path, class: 'nav-link' %>
      </li>
        </strong>

      <li class="nav-item">
        <strong>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </strong>
      </li>
      <% else %>
        <li class="nav-item">
          <strong><%= link_to "Sign up", new_user_registration_path, class: 'nav-link' %>
        </li></strong>
        <li class="nav-item">
          <strong><%= link_to "Sign in", new_user_session_path, class: 'nav-link' %>
        </li></strong>
      <% end %>
    </ul>
  </div>
</nav>